scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'crypto_producer'
    static_configs:
      - targets: ['crypto-producer:8000']

  - job_name: 'spark_consumer'
    static_configs:
      - targets: ['spark-consumer:8001']
  
  - job_name: 'processed_data_consumer'
    static_configs:
      - targets: ['crypto-processed-consumer:8002']
