{
 "title": "Crypto currencies",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "btc_performance", "legendFormat": "__auto" },
    { "expr": "eth_performance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "btc_growth", "legendFormat": "__auto" },
    { "expr": "eth_growth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "btc_diff", "legendFormat": "__auto" },
    { "expr": "eth_diff", "legendFormat": "__auto" }
   ]
  }
 ]
}